name: Greetings

on: [pull_request, issues]

jobs:courier service 
  greeting:good day 
    runs-on: ubuntu-latest
    permissions:allow
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Message that will be displayed on users first issue'
        pr-message: 'Message that will be displayed on users first pull request'
